import UnityPy
import os
import csv
import io
import shutil

GAME_PATH = r"D:\SteamLibrary\steamapps\common\Dust Front RTS Demo\Dust Front RTS_Data"
OUTPUT_DIR = r"D:\SteamLibrary\steamapps\common\Dust Front RTS Demo\localization-tool\output"

# Translation dictionary: English -> Chinese
# Organized by category for clarity
TRANSLATIONS = {
    # === General UI ===
    "otherLocalsFuture": "其他语言本地化正在开发中。",
    "version": "版本：",
    "mainmenu": "主菜单",
    "continue": "继续",
    "no": "否",
    "yes": "是",
    "next": "下一步",
    "save": "保存",
    "start": "启动",
    "play": "游玩",
    "exit": "退出",
    "settings": "设置",
    "back": "返回",
    "or": "或者",
    "reset": "重置 >",

    # === Sound Settings ===
    "volume": "音量",
    "volume-master": "主音量",
    "volume-music": "音乐",
    "volume-voices": "语音",
    "volume-sfx": "音效",

    # === Graphics Settings ===
    "camera": "相机",
    "borderCameraSpeed": "边缘滚动速度",
    "mouseCameraSpeed": "速度",
    "vsync": "垂直同步",
    "fpsLock": "60fps限制",
    "fullScreen": "全屏",
    "cameraInterpolation": "相机插值",
    "cameraShake": "相机抖动",
    "brightness": "亮度",
    "graphics": "图形",
    "res-widescreen-guid": "如果标准分辨率不起作用：使用游戏根目录的配置文件。参数：override res",

    # === Controls ===
    "controls": "控制",
    "controls-dev": "热键修改正在开发中。",
    "controls-text": "Shift + 命令 — 将命令加入队列。\nShift + 左键点击单位/框选 — 添加到选中。\nCtrl + 左键点击单位/框选 — 从选中移除。\n\nT / Ctrl + 1...9 — 添加到快捷编组。\n\nCtrl + Q/A/Z — 本地装备的快捷键。\n\nA（无上下文）— 移动攻击。\nP — 巡逻。\nG（按住）— 倒车。\nB — 全面修理。\nS — 停止命令。\n\nE — 第一技能。\nR — 第二技能。\n\nTab — 在已选单位中切换。\n波浪号（~）— 切换选项标签。\nQ — 选项1。\nW — 选项2。\nA（选项上下文中）— 选项3。\nS — 选项4。\nZ — 选项5。\nX — 选项6。\nD — 选项7。\nC — 选项8。\nF — 选项9。\nV — 选项10。\n\nF1 — 选择所有建造者。\nF2 — 选择所有战斗单位。\nF3 — 选择所有单位。\n\n空格 — 战术暂停。\nEsc — 暂停。\nI — 隐藏界面。\nAlt + 滚轮 — 缩放相机。\nAlt + 按住滚轮 — 旋转相机。",

    # === Task / Mission ===
    "task-defeatCondition-0": "如果你的建筑被摧毁，你将被击败。",
    "task-destroyProd": "摧毁敌人工厂：",
    "task-captPoints": "占领据点：",
    "task-destroyLastUnits": "消灭残余部队：",

    # === Demo Factions ===
    "demoFaction-rebels": "叛军",
    "demoFaction-rebels-info": "更经典的阵营，侧重于机动和轻型单位。\n非常适合作为初始对手，因为其火力天生较弱。",
    "demoFaction-mutants": "变种人",
    "demoFaction-mutants-info": "持续近战压制和重型突击单位构成严重障碍。\n适合经验丰富的指挥官。",
    "demo-selectEnemyFaction": "选择对手",

    # === Battle End Stats ===
    "endStats-stats": "战斗统计：",
    "endStats-time": "时间：",
    "endStats-lossesPeople": "人员伤亡：",
    "endStats-shots": "大口径射击次数：",
    "endStats-lossesUnits": "单位损失：",
    "endStats-lossesSupply": "补给单位损失：",
    "endStats-killedUnits": "消灭敌方单位：",
    "endStats-killedSupply": "消灭敌人（补给单位）：",
    "endStats-killedBuilds": "摧毁建筑：",
    "endStats-resCollected": "收集资源：",

    # === Mission End ===
    "endMisson-victory": "胜利",
    "endMisson-defeat": "失败",
    "endMisson-retreat": "撤退",

    # === Weather ===
    "weather-meteorStart": "注意。雷达探测到平流层碎片坠落。请分散。",
    "weather-meteorEnd": "雷达上已无碎片。",
    "weather-rainStart": "气象中心发来数据。预计有强风暴，请做好准备。",
    "weather-toxicStart": "传感器检测到酸性排放物接近。进入建筑躲避。",
    "weather-toxicEnd": "排放已过，可以放松了。",

    # === Mission Text ===
    "missionText-reinforcements": "增援部队正在途中。",
    "missionText-reinforcementsEnemy": "敌人呼叫了增援。",
    "missionText-endSurvivors": "敌人仍有一支可观的部队。消灭残余！",
    "reinforcementsInMove": "增援部队行进中",

    # === ETA / Placement ===
    "eta-tacticalAbility": "预计时间：",
    "placing-repos": "重新部署",
    "placing-blockedExit": "出口被阻挡",
    "placing-noSpace": "没有空间",
    "placing-mineralsNear": "距矿脉太近",
    "placing-terrainNotFlat": "地形不平",
    "placing-otherPlans": "其他规划冲突",
    "placing-isOutside": "不在建造区域内",
    "placing-onTarget": "放置目标：",

    # === Repair ===
    "genRepairStarted": "修理已开始",
    "genRepairStoped": "取消修理",
    "genRepairNoDamage": "无损伤",

    # === Interaction ===
    "fantomTip": "右键取消。",
    "aim-gui-rear": "遭遇角度：侧后方",
    "aim-gui-front": "遭遇角度：正面",

    # === Unit Info ===
    "object": "单位",
    "doctrine": "全球升级/学说",
    "affects": "影响：",
    "localUpgrade": "局部装备",
    "localUpgradeHave": "此装备可在此处使用：",
    "removeOptions": "移除选项：",
    "addOptions": "添加选项：",
    "required": "需要：",
    "availableUnits": "可用单位",
    "startArmyLeftMenu-info": "从左侧菜单选择单位。",
    "deploy-zones": "部署区域",
    "deploy-reset": "重置",
    "deploy-startBattle": "开始战斗",
    "strikeGroups": "突击编组",
    "curStrikeGroup": "当前编组",
    "startArmy": "你的突击部队",
    "startArmy-info": "用于早期进攻或防御的起始部队。",
    "slideTwhoInfo": "武器及其他 >>>",
    "noStartWeapon": "该单位没有标准武器。",
    "mainParams": "主要属性：",
    "antiAir": "防空能力",
    "sizeType": "尺寸类型：",
    "small": "小型",
    "medium": "中型",
    "large": "大型",
    "special": "特殊",
    "armoreType": "装甲类型：",
    "vehicle": "载具",
    "infantry": "步兵",
    "building": "建筑",
    "hitpoints": "生命值",

    # === Unit Stats ===
    "extraHitpoints": "额外生命值",
    "mainArmore": "主要装甲",
    "rearArmore": "后方和侧方装甲",
    "gasResist": "气体抗性",
    "fireResist": "火焰抗性",
    "areaDmgResist": "范围伤害抗性",
    "movespeed": "移动速度",
    "rotatespeed": "转向速度",
    "mainWeapon": "主要武器：",
    "defaultOptions": "默认选项",
    "basicOptions": "基本选项",
    "sideOptions": "附加选项",
    "mgWeapon": "速射武器",
    "cannonWeapon": "重型武器",
    "projectileWeapon": "火炮武器",
    "turretSpeed": "炮塔转速",
    "hullAim": "车体瞄准",
    "cleanDmg": "纯净伤害",
    "dmgToInfantry": "对步兵伤害",
    "dmgToVehicle": "对载具伤害",
    "dmgToBuild": "对建筑伤害",
    "dmgRadius": "范围伤害半径",
    "reloadTime": "攻击装填时间",
    "reinforementsGm": "来自全球地图的增援。",

    # === Selection Notifications ===
    "groupAssigned": "编组分配至编号：",
    "modeSreenSelect": "限制器开关",
    "modeSreenSelect-info": "开启后：双击选择对象后，同类型单位的选择将限制在屏幕范围内。",
    "allSelect": "选择所有单位。",
    "baseSelect": "选择所有建造建筑。",
    "fSelect-info": "再次点击将移至列表中第一个。",
    "allArmySelect": "选择所有战斗单位。",
    "groupSelected": "编组 {0} 已选中",
    "buildersSelected": "已选择建造者",
    "armySelected": "已选择所有战斗单位",
    "allUnitsSelected": "已选择所有单位",
    "resourcesFull": "收集器已满",
    "tacticalPause": "战术暂停",
    "pause": "暂停",
    "anchor": "锚点",
    "anchor-info": "你的相机将围绕设置锚点时的位置旋转。",
    "noVision": "无视野",

    # === Resources ===
    "materials": "材料",
    "materials-info": "主要资源。用于建造建筑和招募军队。",
    "supply": "补给",
    "supply-info": "战场部队上限。\n建造「补给点」或「补给仓库」来扩展上限。\n无扩展限制。",
    "gears": "零件",
    "gears-info": "此资源用于生产高科技单位和建筑。主要从全球地图补充。",
    "energyPower": "能量",
    "energyPower-info": "基地的网络容量。负值（不足）时，生产大幅减速，炮塔停止工作。",

    # === UI Controls ===
    "sirenaToggle": "警报开关",
    "cameraReset": "重置相机",
    "optionsToBuild": "切换标签",
    "optionsToBuild-info": "此对象有2个选项标签。点击切换。",
    "repairGlobal": "修理",
    "repairGlobal-info": "修理选定的静态对象。修理消耗材料。上方显示当前修理中的对象数量。",
    "prodPause": "生产暂停",
    "prodPause-info": "暂停生产。",
    "prodLoop": "循环生产",
    "prodLoop-info": "生产队列将循环。生产的单位会在资源足够时立即加入队列。",
    "mapLock": "锁定旋转",
    "mapLock-info": "小地图将随相机旋转。",
    "mapKnobScale": "小地图大小",
    "mapKnobScale-info": "滚动鼠标滚轮改变大小。",
    "mapKnobRot": "小地图旋转",
    "mapKnobRot-info": "滚动鼠标滚轮改变旋转。",
    "modeBehaviour": "行为模式",
    "modeBehaviour-info": "两种模式：防御和进攻。防御模式下单位固守阵地。进攻模式下主动出击。",
    "attackPriority": "攻击优先级",
    "attackPriority-info": "当目标类型进入射程时，单位将自动切换攻击该类型。",
    "attackBlock": "禁止攻击",
    "attackBlock-info": "禁止单位开火或瞄准目标。",
    "aclick": "移动攻击",
    "aclick-info": "指定单位推进的位置。单位将沿该方向移动并攻击射程内的一切。",
    "patrolOrder": "巡逻",
    "patrolOrder-info": "单位巡逻该区域。",

    # === Strike Groups ===
    "strikeGroupMain": "主突击编组",
    "strikeGroupMain-info": "可立即部署在地图上的部队。你还将获得一个移动指挥所来建造基地。",
    "strikeGroupAdd": "来自「全球地图」的增援",
    "strikeGroupAdd-info": "演示版没有全球地图，但你可以指定增援时到达地图的部队。\n你选择的部队越多，等待下一次增援的时间越长。\n\n点击选择。",

    # === Difficulty ===
    "difficultyLevel": "敌人难度",
    "difficultyLevel-info": "难度倍率影响敌人的整体难度。\n\n参考值：\n+0.5 - 简单难度。\n+1.5 - 中等难度。\n+3 - 困难难度。\n\n倍率超过2.5后AI开始作弊。",
    "enemyBaseScale": "敌方基地规模",
    "enemyBaseScale-info": "地图上生成的建筑数量。\n生成的建筑数量影响游戏难度和持续时间。",

    # === Units (Rebels) ===
    "unit-bmp": "步兵战车",
    "unit-bmp-info": "重型步兵战车，装甲良好。",
    "unit-rifleSquad": "步枪兵",
    "unit-rifleSquad-info": "步枪兵是轻步兵。以数量完成任务。",
    "unit-brem": "装甲抢救车",
    "unit-brem-info": "主要维修车辆。可修理载具并修复受损的超重型载具。",
    "unit-bronenosets": "铁甲舰",
    "unit-bronenosets-info": "铁甲舰是重型突击坦克。拥有非常坚固的装甲，可在战场上恢复生命值。",
    "unit-btr": "装甲运兵车",
    "unit-btr-info": "装备防空机枪的装甲运兵车。",
    "unit-btrFlamer": "喷火装甲运兵车",
    "unit-btrFlamer-info": "基于标准装甲运兵车的喷火车辆。轻型装甲。速度高于平均水平。点燃地形。",
    "unit-armcar": "装甲车",
    "unit-armcar-info": "防弹装甲车辆。非常适合侦察。轻型防空炮，极高速度。",
    "unit-dreadHowitzer": '"无畏"榴弹炮',
    "unit-dreadHowitzer-info": "超重型火炮。可在战场上自由移动的最强大火炮。",
    "unit-dreadnought": "无畏舰",
    "unit-dreadnought-info": "超重型火炮。防御、巩固阵地和长期围攻敌方防线不可或缺的载具。移动模式下可支援进攻。",
    "unit-flameTank": "喷火坦克",
    "unit-flameTank-info": "装甲喷火车辆。流式喷火器持续点燃地面。耐久度高，机动性低。",
    "unit-combine": "联合收割机",
    "unit-combine-info": "收集地表矿物的工作车辆。经济基础。越多越好。",
    "unit-massInfantry": "大规模步兵",
    "unit-massInfantry-info": "大型步兵编队。轻装甲步枪兵和反坦克火箭筒手组成的增强编队。",
    "unit-gorbTank": "驼背坦克",
    "unit-gorbTank-info": "量产型重型突破坦克，全方位装甲。无炮塔。\n对建筑和大型集群有效。",
    "unit-atSquad": "反坦克小组",
    "unit-atSquad-info": "装备反坦克武器的轻步兵。\n命中时对载具和建筑造成重大伤害。",
    "unit-molot": '"锤子"榴弹炮',
    "unit-molot-info": "自行榴弹炮。主要且最常用的火炮。\n大量使用时威力强大。需要展开才能开火。",
    "unit-brutes": "蛮兵",
    "unit-brutes-info": "缓慢、笨拙、畸形，但有武装的炮灰。\n综合体随心所欲地制造他们，但对你来说，这是免费的「蛮力」。",
    "unit-spotters": "观测员",
    "unit-spotters-info": "由狙击手和炮手组成的小组。使用肩扛式重型电台，可在任何距离引导火炮轰击阵地。",
    "unit-heavyInfantry": "突击小组",
    "unit-heavyInfantry-info": "多功能步兵单位。包括重型防空射手和步枪小组。自动炮手非常强大且耐久。",
    "unit-supvehicle": "机动支援营地",
    "unit-supvehicle-info": "移动步兵营地提供步兵支援。",
    "unit-mainTank": '"T-50B"坦克',
    "unit-mainTank-info": "主战坦克。通用且广泛部署，履带式。可执行进攻。对载具和建筑有效。",
    "unit-rszo": '"旋风"火箭炮',
    "unit-rszo-info": "射程远，但最小射程也远。大范围面杀伤，散布较大。大燃烧载荷弹药。",
    "unit-yak": "P-2",
    "unit-yak-info": "截击机。重机枪可应对任何空中目标。",
    "unit-aaTank": '"排气"高射炮',
    "unit-aaTank-info": "重型自行高射炮。击落空中目标，可对地面目标直瞄射击。",
    "unit-zeppelin": "重型运输车",
    "unit-zeppelin-info": "运输载具。可用轻机枪自卫。",
    "unit-mcv": "移动建造中心",
    "unit-mcv-info": "移动装配车间是建造工人的移动指挥所。负责基地建设和与指挥部联络。",
    "unit-mgTurret": '"AK-30"炮塔',
    "unit-mgTurret-info": "多功能炮塔，可对抗步兵并击落低空飞行的敌机。可移动。",
    "unit-repairPad": "维修平台",
    "unit-repairPad-info": "修理驶入平台的载具。可移动。",
    "unit-bigBrem": '"力士"重型维修车',
    "unit-bigBrem-info": "重型维修车辆。修理附近区域的载具。还有步兵治疗升级。",
    "unit-cerber": "刻耳柏洛斯",
    "unit-cerber-info": "骨骼坚固的突击型装甲变异体。战斗中可轻松恢复生命。不灵活，有两门火炮。",
    "unit-corrupter": "宿主腐蚀者",
    "unit-corrupter-info": "独特的召唤炮兵。攻击时通过地面发射充当鞭子的微型蠕虫，同时召唤蠓虫群。\n近战时脆弱。",
    "unit-fatSwarm": "强壮爬行者",
    "unit-fatSwarm-info": "爬行者是缩小版刻耳柏洛斯。有装甲，缓慢，对建筑伤害高。",
    "unit-gnus": "食水泥虻",
    "unit-gnus-info": "也能消化金属。虻能很好地吞噬载具并迷惑步兵。",
    "unit-mutantHarv": "大型采集者",
    "unit-mutantHarv-info": "变种人采集者是大型、缓慢的驳船，具有令人印象深刻的材料运输能力。是变种人的主要经济单位。",
    "unit-massMeat": "肉体聚合体",
    "unit-massMeat-info": "复活并站立起来的各种东西的堆叠。生命值极高，体型巨大。",
    "unit-meat": "肉块",
    "unit-meat-info": "有腿的小块肉。用腐烂射击有效打击步兵。",
    "unit-gigant": "巨人",
    "unit-gigant-info": "巨人系列变异体。在各方面都极具破坏力。",
    "unit-muha": "变异飞虫",
    "unit-muha-info": "装备火箭发射器的大型变异飞虫。飞行速度快。",
    "unit-warriors": "变异战士",
    "unit-warriors-info": "变异体步枪步兵。手臂中长出机枪的超龄者能以巨大优势压制同类。",
    "unit-oldTank": "老旧坦克",
    "unit-oldTank-info": "用废料和其他坦克零件组装的旧式三履带坦克。性能中等，略偏重步兵打击。",
    "unit-scumMutant": "病态变异体",
    "unit-scumMutant-info": "重型变异步兵。单独行动，对重型武器脆弱，但在交火中无人能敌。",
    "unit-spider": "蜘蛛",
    "unit-spider-info": "技术上不是蜘蛛，但因细腿而得名。速度极快，对载具非常有效。适合侧翼包抄。几乎没有耐久。",
    "unit-swarm": "蠕虫群",
    "unit-swarm-info": "变异体食物和突击力量兼而有之。如果能接近，能迅速扫清步兵。",
    "unit-toxicArtillery": "腐蚀炮",
    "unit-toxicArtillery-info": "远程火炮。以极高弹道和远距离发射破坏性载荷弹药。对建筑有效。",
    "unit-baloon": "战斗气球",
    "unit-baloon-info": "在中低空飞行的轻型热气球。装备火箭发射器攻击地面目标。",
    "unit-sonicWagon": "声波炮兵",
    "unit-sonicWagon-info": "清除民用系统堵塞的专用车辆。也适合摧毁肉体和轻型载具。",
    "unit-assaultTruck": "突击卡车",
    "unit-assaultTruck-info": "重型突破车辆。装备大型防空机枪和炮塔机炮。生存力高，但装甲并非最佳。",
    "unit-buggy": "皮卡",
    "unit-buggy-info": "装备重机枪的轻型车辆。高速度，轻装甲，非常适合侦察和步兵交战。",
    "unit-wheeledDom": "移动房屋",
    "unit-wheeledDom-info": "在部署区域内提供指挥的巨型棚屋式建筑。四周可选多种武器。叛军和匪徒有时用作突击单位。",
    "unit-smallTank": '"M-40"坦克',
    "unit-smallTank-info": "基于远古原型的轻型坦克。",
    "unit-monocycle": "T-2独轮车",
    "unit-monocycle-info": "独轮车的重型版本。有轻武器防护，但仍然快速。",
    "unit-ballista": "弩炮",
    "unit-ballista-info": "机械化能量弩炮。近距离重型火炮。对指定位置快速放电造成巨大伤害。机动性极低。",
    "unit-warbot": "无人机小队",
    "unit-warbot-info": "机器人升级任务中最轻的单位。有装甲，相对较快，小队有2架无人机。对步兵非常有效。",
    "unit-robotHarv": "采集无人机",
    "unit-robotHarv-info": "用于收集地图上有用资源的采集器。升级侧重于采集和运输速度而非容量，因此需要不少。",
    "unit-liner": "重型班轮",
    "unit-liner-info": "为基地防御和战斗侦察设计的大型机器人载具。",
    "unit-seeker": "搜索者",
    "unit-seeker-info": "反重力防空坦克。发射范围伤害导弹。对步兵也有效。难以穿透装甲载具。",
    "unit-spear": "弧光之矛",
    "unit-spear-info": "机器人升级的重型火炮。对所有目标都非常强大，具有移动底盘。",
    "unit-roboTank": "等离子坦克",
    "unit-roboTank-info": "机器人主战坦克，重力驱动。同类中最佳。",
    "unit-devastator": '"毁灭者"坦克',
    "unit-devastator-info": "装备基于机器人技术的能量武器的重型载具。炮塔还有机枪。",
    "unit-tankBeam": '"光束"坦克',
    "unit-tankBeam-info": "装备重型等离子切割器的坦克。",
    "unit-marauder": "掠夺者",
    "unit-marauder-info": "装备火箭发射器的小型卡车。",
    "unit-tvmech": "电视机",
    "unit-tvmech-info": "又一款过去的载具。雇佣兵版本包括更强的装甲和50毫米自动炮。",
    "unit-rafa": "拉法",
    "unit-rafa-info": "装备四枚导弹的快速小型三轮车。",
    "unit-scorpion": "蝎子",
    "unit-scorpion-info": "废土炮兵。简单直接。性能中等。",
    "unit-heavyBomber": "重型轰炸机",

    # === Buildings (Rebels) ===
    "build-oilPump": "废弃矿井",
    "build-oilPump-info": "修复此建筑可获得额外资源。",
    "build-medPoint": "医疗站",
    "build-medPoint-info": "医疗站在小范围内治疗步兵。随时间损坏。",
    "build-largePipe": "大型管道",
    "build-heavyWall": "重型墙壁",
    "build-heavyWall-info": "超级混凝土制成的模块化墙壁。非常坚固。",
    "build-heavyCover": "重型掩体",
    "build-heavyCover-info": "由坚固材料制成的掩体，步兵可在其后坚持更久。",
    "build-armory": "军械库",
    "build-armory-info": "部分T3单位需要此建筑。\n\n每增加一座建筑，新部队伤害提升5%。最高30%。",
    "build-atTurret": '"AK-125"炮塔',
    "build-atTurret-info": "固定反坦克炮塔。内置自动装弹机，确保高射速。",
    "build-avanpost": "前哨站",
    "build-avanpost-info": "前哨站是区域间通信的纽带。此类建筑部署在废土中。",
    "build-barn": "仓库",
    "build-barn-info": "扩展补给上限。",
    "build-bigBarn": "大型仓库",
    "build-bigBarn-info": "大幅扩展补给上限。有利于更快部署，更适合冲突后期。",
    "build-barracks": "兵营",
    "build-barracks-info": "步兵单位的主要生产建筑。可在此召唤各类步兵到战场。",
    "build-bunker": "碉堡",
    "build-bunker-info": "可容纳步兵编队的坚固防御建筑。在相应升级下还能恢复步兵生命值。",
    "build-largeCrane": "建筑起重机",
    "build-largeCrane-info": "增加一条建筑建造队列。大幅扩展建造区域。\n\n修理小范围内的载具。",
    "build-tankFactory": "载具工厂",
    "build-tankFactory-info": "载具单位的主要生产建筑。\n\n连续建造可获得生产折扣。",
    "build-flamerTurret": "喷火炮塔",
    "build-flamerTurret-info": "流式喷火器持续点燃区域，对步兵和轻型载具造成重大伤害。视野和瞄准角度有限。",
    "build-generator": "发电站",
    "build-generator-info": "增加网络容量。容量为负时，大部分防御设施将停止工作，部队生产减速。",
    "build-smallgen": "轻型发电机",
    "build-smallgen-info": "廉价的小型发电机。",
    "build-massfab": "物质制造器",
    "build-massfab-info": "物质制造器。内部催化剂消耗大量能量，从深层矿粉中生产标准资源。",
    "build-radar": "雷达",
    "build-radar-info": "用于侦察和扫描地形。也高亮显示敌方静态建筑。",
    "build-refinery": "加工厂",
    "build-refinery-info": "矿物加工厂。将矿物加工为主资源。\n\n处理能力约等于两台联合收割机。",
    "build-silo": "储藏室",
    "build-silo-info": "扩展存储材料（主资源）的最大上限。",
    "build-resStation": "资源平台",
    "build-resStation-info": "通过此建筑可访问全球地图的资源。运输机将自动卸载可用资源。",
    "build-complector": "综合体",
    "build-complector-info": "逐步生产「蛮兵「的生物工程站。\n\n附加建筑机制：\n- 附近兵营获得5%折扣。\n- 发电站加速「蛮兵「生产。\n- 储藏室增加「蛮兵「最大数量。",
    "build-foundry": "铸造厂",
    "build-foundry-info": "部分T3单位需要此建筑。\n\n每增加一座建筑，新载具耐久提升10%。最高50%。",
    "build-supplyDepot": "补给站",
    "build-supplyDepot-info": "持续为部队提供补给。也开放临时补给部署。",
    "build-trench": "战壕",
    "build-trench-info": "相比其他防御设施，最便宜且建造最快。",
    "build-yarus": '"雅鲁斯"发射井',
    "build-yarus-info": "实验性发射制造井，生产装有高爆弹头的重型导弹并控制其发射。",
    "build-subgen": "附加发电机",
    "build-subgen-info": "固体燃料发电机。产生额外功率。可安装在普通发电站上。",
    "buid-aaStratTower": "防空塔",
    "buid-aaStratTower-info": "重型防空塔。防空炮在远距离击落空中目标，造成大范围伤害。最好在出现后尽快摧毁或占领。",
    "build-civsStructs": "民用设施",
    "object-ostov": "废墟",
    "object-container": "集装箱",

    # === Buildings (Mutants) ===
    "build-midStrat": "特殊设施",
    "build-midStrat-info": "具有特定用途的专业化建筑。理论上，控制它们将获得优势。",
    "build-ostov": "废墟",
    "build-strategicStructure": "战略建筑",
    "build-strategicStructure-info": "执行战略功能的大型结构，无论在全球地图还是战术模式中，取决于任务。",
    "build-flyPod": "飞虫培育器",
    "build-flyPod-info": "生产飞行变异体的生物工厂。",
    "build-mutantBarrack": "变异体巢穴",
    "build-mutantBarrack-info": "巢穴般的变异体住所。驻扎和装备步兵单位，可召唤到战场。步兵单位的主要生产建筑。",
    "build-bioSpot": "生物气泡",
    "build-bioSpot-info": "扩展补给上限的通用建筑和材料储藏室。也提供能量。",
    "build-bioCapsule": "胶囊",
    "build-bioCapsule-info": "单位存储胶囊。释放其中的变异体。",
    "build-mutantFactory": "构筑巢穴",
    "build-mutantFactory-info": "生产生物机器、重型变异体和类似机械载具的工厂。载具单位的主要生产建筑。",
    "build-oddFlak": "奇特防空炮",
    "build-oddFlak-info": "击落敌方飞行器的速射炮塔。",
    "build-massMeatPool": "肉体聚合池",
    "build-massMeatPool-info": "培养巨型变异体的大型建筑。静态形式下充当远程火炮，战场上极难忽视。",
    "build-bioRefinery": "消化矿场",
    "build-bioRefinery-info": "加工矿物的生物车间。变异体的主要经济建筑。",
    "build-spitTurret": "吐痰炮塔",
    "build-spitTurret-info": "大型火炮炮塔。对载具和步兵表现出色，但弹道极高，初速低。",
    "build-mutantPost": "观察芽",
    "build-mutantPost-info": "区域控制哨所。",
    "build-wormTurret": "地下蠕虫",
    "build-wormTurret-info": "突然沿线和范围造成伤害的蠕虫。对够得着的一切都有效。无火炮难以命中。",
    "build-airPit": "飞行器坑",
    "build-airPit-info": "用废料组装飞行器的车间。",
    "build-slavePost": "主人前哨",
    "build-slavePost-info": "大型奴隶仓库。有趣的是：通常将被捕获的合成人编为奴隶，因为几乎别无选择。",
    "build-troopShack": "武装分子棚屋",
    "build-troopShack-info": "匪徒窝点。各类军事团体驻扎在此，以扩大影响力。招募叛军步兵的主要建筑。",
    "build-machineShop": "发动机车间",
    "build-machineShop-info": "战利品、被盗零件和未完成项目的废品场。叛军在此建造载具。",
    "build-oldGenerator": "发电机",
    "build-oldGenerator-info": "普通的、稍显老旧的固体燃料发电机。增加网络功率。",
    "build-oldFlak": "防空炮",
    "build-oldFlak-info": "圆形炮塔中的两挺重机枪。对空和对地射击。",
    "build-oldSilos": "球形筒仓",
    "build-oldSilos-info": "简单的材料储藏室。",
    "build-oldTower": "瞭望塔",
    "build-oldTower-info": "控制领土的观察哨。",
    "build-robotBarrack": "轻型步兵车间",
    "build-robotBarrack-info": "组装步兵类部队。机器人升级的主要步兵建筑。",
    "build-robotFactory": "机甲工厂",
    "build-robotFactory-info": "重型载具在此出现。机器人升级的主要载具建筑。",
    "build-robotGenerator": "反应堆",
    "build-robotGenerator-info": "扩展网络允许功率，允许建造更多建筑而不失去炮塔功能或降低部队生产速度。",
    "build-robotRefinery": "净化中心",
    "build-robotRefinery-info": "采集无人机在此存放矿物，然后产出建造和生产用的材料。主要经济建筑。",
    "build-robotSilo": "储藏室",
    "build-robotSilo-info": "存储建造军队和基地的材料。扩展最大材料储量。",
    "build-plasmaTurret": "等离子炮塔",
    "build-plasmaTurret-info": "对抗敌方载具的等离子切割器。持续纯净伤害烧穿任何装甲。",

    # === Abilities ===
    "ability-artilleryGuid": "火炮引导",
    "ability-artilleryGuid-info": "所有处于「固守阵地「模式的火炮对选定位置进行任意距离轰击。\n\n如果没有处于所需模式的火炮，此能力将被阻止。",
    "ability-regroupHeal": "重组",
    "ability-regroupHeal-info": "补充步兵编队并恢复其生命值。",
    "ability-exit": "离开",
    "ability-exit-info": "离开建筑或载具。",
    "ability-setMode": "关闭/开启",
    "ability-setMode-info": "根据当前模式停止或开始工作。",
    "ability-craneArrow": "引导吊臂",
    "ability-craneArrow-info": "起重机将吊臂指向指定单位的方向。",
    "ability-setupPos": "加固",
    "ability-setupPos-info": "在当前位置加固。",
    "ability-setupState": "展开",
    "ability-setupState-info": "对象展开为静态对象。在静态模式下，反向收起为移动状态。",
    "ability-subArmore": "再生装甲",
    "ability-subArmore-info": "再生装甲超载为载具提供额外耐久。小心！附近步兵会受到严重伤害。\n\n如果载具耐久较低，超载可能致其死亡。",
    "ability-flakAmmo": "防空弹药",
    "ability-flakAmmo-info": "单位更换为防空弹药。使其能对空射击并对步兵造成更高伤害。",
    "ability-selectInBunker": "选择内部单位",
    "ability-selectInBunker-info": "此对象提供选择其中驻扎单位的功能。",
    "ability-forcedFire": "区域炮击",
    "ability-forcedFire-info": "强制炮击。如果有命令队列，火炮将轰击选定区域约10秒。",
    "ability-startHarvest": "开始工作",
    "ability-startHarvest-info": "自动寻找合适的矿物并开始开采。如果储藏室接近满载，将前往卸载。",
    "ability-harvDrop": "回收联合收割机",
    "ability-harvDrop-info": "运输机将新的联合收割机送到战场。",
    "ability-freeDefence": "警卫",
    "ability-freeDefence-info": "召唤6支警卫编队。可帮助抵御敌人或支援进攻。不需要补给。",
    "ability-regenStim": "再生刺激剂",
    "ability-regenStim-info": "恢复生命值。",
    "ability-mineSetup": "布设地雷",
    "ability-mineSetup-info": "布设压力地雷。地雷不会立即激活。小心，你自己也可能碾到。",
    "ability-scan": "扫描",
    "ability-scan-info": "揭开指定位置的战争迷雾。",
    "ability-resReloc": "停止运输",
    "ability-resReloc-info": "暂停从全球地图召唤资源。再次点击恢复。",
    "ability-repair": "修理",
    "ability-repair-info": "选择要修理的目标。",
    "ability-rocketLaunch": "发射导弹",
    "ability-rocketLaunch-info": "战术导弹将对指定位置造成重大伤害。发射前需侦察区域。",
    "ability-siegeMode": "火炮阵地",
    "ability-siegeMode-info": "将所有系统转为火炮模式。对远距离区域开火。",
    "ability-smokeCurtain": "烟幕",
    "ability-smokeCurtain-info": "烟雾为敌我双方部队创造瞄准障碍。",
    "ability-artShot": "强力射击",
    "ability-artShot-info": "主炮对选定位置/目标开火。",

    # === Support Abilities ===
    "support-carpetBomber": "燃烧尾迹",
    "support-carpetBomber-info": "呼叫重型轰炸机进行凝固汽油弹轰炸。轰炸机可能被击落。\n\n射程：3个扇区。",
    "support-gasBomber": "毒气弹",
    "support-gasBomber-info": "呼叫重型轰炸机投掷毒气弹。轰炸机可能被击落。\n\n射程：3个扇区。",
    "support-combineDrop": "空投联合收割机",
    "support-combineDrop-info": "将联合收割机空投到战场。",
    "support-heavyBomber": "重型炸弹",
    "support-heavyBomber-info": "呼叫投掷5枚大型炸弹的重型轰炸机。炸弹造成范围伤害，爆炸中心伤害更高。轰炸机可能被击落。\n\n射程：3个扇区。",
    "support-desant": "空降",
    "support-desant-info": "空降一支小型步兵分队。",
    "support-scouting": "区域照明",
    "support-scouting-info": "长时间揭开选定区域的战争迷雾。",
    "support-techReinforce": "建筑增援",
    "support-techReinforce-info": "总部紧急调拨一些额外零件。",
    "support-interceptor": "截击机",
    "support-interceptor-info": "呼叫P-2截击机在天空中维持持续巡逻。也可用于空中侦察。\n与火炮完美配合。\n\n射程：4个扇区。",

    # === Doctrine (Rebels) ===
    "doctrine-bunkers": "碉堡",
    "doctrine-bunkers-info": "现在可以建造碉堡。与炮塔不同，不需要电力。",
    "doctrine-energetics": "附加发电机",
    "doctrine-energetics-info": "解锁发电机附加建筑。移动建造中心还获得便携式发电机，提供初始网络功率储备。",
    "doctrine-harvDrop": "紧急呼叫",
    "doctrine-harvDrop-info": "加工厂可以呼叫额外的联合收割机作为工人增援。在无法在工厂订购时非常有用。",
    "doctrine-macroEco": "宏观经济",
    "doctrine-macroEco-info": "允许建造物质制造器。被动资源增长在游戏后期几乎不可或缺。\n该物体会爆炸。",
    "doctrine-repairExpansion": "维修扩展",
    "doctrine-repairExpansion-info": "作为起重机的替代，获得重型维修车辆，提供小型建造区域，善于修理载具并可转移位置。",
    "doctrine-tacticalRockets": "战术导弹",
    "doctrine-tacticalRockets-info": "实验性发射制造井，生产装有高爆弹头的重型导弹并控制其发射。",
    "doctrine-heavyTurrets": "重型炮塔",
    "doctrine-heavyTurrets-info": '"AK-125"炮塔对轻型、中型和重型载具有效。加固底座提供更高耐久，观察设备提供更大射程。',
    "doctrine-flamerTurrets": "喷火炮塔",
    "doctrine-flamerTurrets-info": "点燃地形。喷射混合物的温度甚至可以摧毁轻型载具。\n\n非常适合消灭大群敌人。",
    "doctrine-mgTurrets": "机枪炮塔",
    "doctrine-mgTurrets-info": '"AK-30"防空机动炮塔具有高射速和对步兵伤害。可有效打击轻型载具和空中目标。\n\n可移动和挖掘工事。挖掘后无法再移动。',
    "doctrine-assault": "突击学说",
    "doctrine-assault-info": "解锁一系列突击和清扫武器。允许正面攻击和直接冲突。",
    "doctrine-repairability": "可修复性",
    "doctrine-repairability-info": "如果联合收割机受损，可以修理。",
    "doctrine-medic": "移动总部",
    "doctrine-medic-info": "允许建造移动步兵营地。",
    "doctrine-prototypes": "原型机",
    "doctrine-prototypes-info": "雇佣兵将有机会提供古代超重型载具或基于失传技术的原型机。",
    "doctrine-purger": "清洗学说",
    "doctrine-purger-info": "快速危险的喷火装甲运兵车配合突破防御工事的重型突击坦克。",
    "doctrine-rszo": "火箭炮",
    "doctrine-rszo-info": "将「锤子「管式火炮替换为「托帕兹「火箭炮。",
    "doctrine-siege": "围攻学说",
    "doctrine-siege-info": "围攻学说解锁一系列围攻武器。以优势火力和大规模炮击为特点。",
    "doctrine-support": "支援学说",
    "doctrine-support-info": "解锁重型步兵战车。",
    "doctrine-tanks": "坦克学说",
    "doctrine-tanks-info": "装备防空重机枪的宽敞装甲运兵车和装备反坦克炮的主战坦克。适用于任何情况的通用学说。",
    "doctrine-armoredInfantry": "装甲步兵",
    "doctrine-armoredInfantry-info": "解锁配备重型禁卫军伞兵的步兵编队。",
    "doctrine-barracksGrades": "兵营塔楼",
    "doctrine-barracksGrades-info": "兵营获得一系列可选局部升级。医疗塔楼快速治疗区域内的步兵，步兵塔楼允许使用更大更强的步枪编队。",

    # === Upgrades (Rebels) ===
    "upgrade-siegeHowitzer": "围攻榴弹炮",
    "upgrade-siegeHowitzer-info": "无畏舰炮塔替换为重型榴弹炮平台。\n\n移动中无法开火。",
    "upgrade-sideArmore": "侧裙装甲",
    "upgrade-sideArmore-info": "提供少量侧方防护。",
    "upgrade-medBunker": "医疗碉堡",
    "upgrade-medBunker-info": "碉堡。治疗区域内的步兵。",
    "upgrade-autoCannons": "自动炮",
    "upgrade-autoCannons-info": "炮塔机炮。对载具伤害高。",
    "upgrade-heavyFlamers": "重型喷火器",
    "upgrade-heavyFlamers-info": "为坦克装备重型喷火器。点燃地面对步兵造成巨大伤害。",
    "upgrade-harvRocket": "导弹炮塔",
    "upgrade-harvRocket-info": "联合收割机顶部安装导弹炮塔。用于自卫。",
    "upgrade-horn": "扩音器",
    "upgrade-horn-info": "鼓舞战士并增强其体能的扩音器。",
    "upgrade-mgTurrets": "机枪炮塔",
    "upgrade-mgTurrets-info": "载具装备机枪炮塔。",
    "upgrade-rocketTurrets": "导弹炮塔",
    "upgrade-rocketTurrets-info": "载具装备导弹炮塔。",
    "upgrade-medBlock": "医疗模块",
    "upgrade-medBlock-info": "在大范围内缓慢恢复步兵生命值。",
    "upgrade-medTower": "医疗塔楼",
    "upgrade-medTower-info": "塔楼额外治疗小范围内的步兵。",
    "upgrade-mineKit": "布雷套件",
    "upgrade-mineKit-info": "布雷套件。",
    "upgrade-massFlaks": "防空炮",
    "upgrade-massFlaks-info": "将装甲车替换为「排气「防空系统。",
    "upgrade-repMobility": "机动性",
    "upgrade-repMobility-info": "允许维修平台移动。",
    "upgrade-infantryTower": "步兵塔楼",
    "upgrade-infantryTower-info": "步兵塔楼将普通步枪兵替换为更大的常规步兵编队。塔楼还能发射大口径狙击步枪。",
    "upgrade-trenching": "加固",
    "upgrade-trenching-info": "战壕用支撑和顶棚加固，变成小型碉堡。",
    "upgrade-barricades": "街垒",
    "upgrade-barricades-info": "炮塔周围建造额外街垒，提高生存力。失去移动能力（如有）。",
    "upgrade-nars": "非制导火箭",
    "upgrade-nars-info": "战斗单位装备非制导火箭。",
    "upgrade-miniCrane": "迷你起重机",
    "upgrade-miniCrane-info": "小型起重机扩展为建筑增加额外建造队列。可同时建造2座不同建筑。",

    # === Items ===
    "item-apShells": "穿甲弹",
    "item-apShells-info": "弹药中增加的穿甲质量提高对载具的伤害。",
    "item-areaResist": "防爆层",
    "item-areaResist-info": "以直接伤害防护为代价，提高载具的范围伤害抗性。",
    "item-armoreAdd": "附加装甲衬层",
    "item-armoreAdd-info": "通过工程学的魔力，我们在载具中找到了附加装甲的空间。增强装甲。",
    "item-artilleryLoader": "火炮自动装弹机",
    "item-artilleryLoader-info": "更强大的火炮自动装弹机。加速火炮装填，但需要更多空间，影响耐久。",
    "item-canonsLoader": "通用自动装弹机",
    "item-canonsLoader-info": "更通用的自动装弹机。更紧凑，但效率较低。",
    "item-compositAdd": "附加复合装甲",
    "item-compositAdd-info": "战斗室容纳额外的装甲尺寸，减少自动装弹机和武器装填区域的空间。",
    "item-concrete": "超级混凝土",
    "item-concrete-info": "增加建筑耐久。",
    "item-explShells": "增强爆破弹",
    "item-explShells-info": "弹药中更多炸药。对步兵和建筑造成更多伤害。",
    "item-firePayload": "燃烧载荷",
    "item-firePayload-info": "弹药中增加了燃烧混合物，在弹着点燃烧，以穿甲能力为代价。",
    "item-fireSuit": "防火服",
    "item-fireSuit-info": "在士兵装备中嵌入特殊防火层。防护火灾。",
    "item-gasPayload": "毒气载荷",
    "item-gasPayload-info": "弹药中增加了毒气弹头。在效果区域产生毒气云，窒息敌人。毒气可引爆。",
    "item-infantryAddHp": "强化生命",
    "item-infantryAddHp-info": "为生物体提供增强整体生存力的改造方案。有副作用。",
    "item-infantryExtraHp": "防弹背心",
    "item-infantryExtraHp-info": "一次性步兵防弹衣。丢失后不补发。",
    "item-morePayloads": "增加载荷",
    "item-morePayloads-info": "如果弹药含有燃烧、毒气或有毒弹头，其持续时间和效果区域增加。\n否则此改造无用。",
    "item-radio": "电台",
    "item-radio-info": "略微增加攻击距离。",
    "item-scope": "全景瞄准镜",
    "item-scope-info": "增加攻击距离，但需要装甲空间安装。",
    "item-steel": "特殊钢材",
    "item-steel-info": "载具以总耐久为代价获得装甲强化。",
    "item-stimulators": "兴奋剂",
    "item-stimulators-info": "长途行军的兴奋剂。",
    "item-subcalShells": "次口径战斗载荷",
    "item-subcalShells-info": "以通用性为代价大幅增加对载具的伤害。",
    "item-turretRot": "炮塔驱动",
    "item-turretRot-info": "将动力从发动机转移到炮塔驱动，提高炮塔转速。",

    # === Mutant Units ===
    "unit-gnus-info": "也能很好地消化金属。虻能很好地吞噬载具并迷惑步兵。",

    # === Tutorial (from textasset_165) ===
    "tutorial": "教程",
    "startScreen-demo": "向胜利之路迈进的勇士，\n我向你致敬！\n\n<size=30>\n你有机会体验第四工业帝国的战争机器。\n\n此演示的目的是展示无全球地图的RTS战斗。\n\n祝你好运，将军。\n</size>",
    "startScreen2-demo": "你好！\n\n<size=30>\n请通过Steam运行此演示。\n游戏将参与商店统计，这将帮助项目。\n\n如果演示不可用，「Dust Front RTS「已撤退进行重组，补充弹药和给养，以便以全新力量回归。\n开发工作持续推进。\n</size>",
    "endScreen-demo": "感谢游玩！\n<size=25>\n完整版将提供更多内容，包括其他单位、建筑、任务，当然还有游戏的核心——全球地图征服。\n\n尝试不同的难度、敌方基地规模和单位——游戏可提供不同的体验。\n</size>",
    "demo-fightingFor": "你正在为第四工业帝国而战。",
    "demo-achivInfo": "该值表示最大难度倍率。",
    "demo-newRecord": "难度记录被打破！",
    "demo-achiv-base1": "围攻敌方基地胜利。",
    "demo-achiv-base2": "x2规模基地围攻胜利",
    "demo-achiv-base3": "x3规模基地围攻胜利",
    "demo-achiv-base4": "x4规模基地围攻胜利",
    "demo-achiv-popupTitle": "获得新成就！",
    "tip-demoShiftSetup": "按住Shift可加速设置和添加。",
    "wishlist-text-0": "如果喜欢此演示，请将游戏加入愿望单！",
    "wishlist-text-1": "谢谢，游戏发布时你将收到通知！",
    "openSteam": "打开Steam",
    "addToWishlist": "加入愿望单",
    "tutorial-gui-name": "界面教程",
    "tutorial-overall-name": "综合教程",
    "tutorial-deploy-0": "这是你选择的部队。需要将他们部署到战场上才能开始战斗。",
    "tutorial-deploy-0a": "你还可以通过滚动鼠标滚轮调整编队大小。",
    "tutorial-deploy-1": "部署所有单位后，战斗开始按钮将出现。\n\n准备好时点击它。",
    "tutorial-deploy-2": "此面板是战术能力。它们在全球地图上设置，但演示版提供预设。",
    "tutorial-deploy-3": "这里显示你当前的任务。\n主要任务为白色。\n附加任务为黄色。\n\n目前你只有主要（必需）任务。",
    "tutorial-deploy-3a": "本场战斗的任务：",
    "tutorial-deploy-3b": "你需要控制三个区域。每个区域提供被动资源收入。\n\n敌人会尝试夺回。要在区域内驻扎部队或建筑来占领。",
    "tutorial-deploy-3c": "你还需要摧毁敌方关键建筑。\n它们在小地图上标记。\n\n如果你的建筑被摧毁，你将被击败。",
    "tutorial-deploy-4": "小地图上显示了对象点。\n\n<color=#808080>灰色点</color> — 中立。\n<color=#FF4444>红色点</color> — 敌方。\n<color=#44FF44>绿色点</color> — 己方。\n<color=#A47068>深橙色</color> — 资源。\n<color=#7ECAE5>蓝色符号</color> 表示主要任务对象。\n\n圆圈标记占领点。",
    "tutorial-deploy-5": "相机移动：",
    "tutorial-deploy-5a": "键盘：",
    "tutorial-deploy-5b": "按住鼠标中键：",
    "tutorial-deploy-5c": "也可以通过屏幕边缘移动相机。\n\n缩放相机：按住左Alt并滚动鼠标滚轮。",
    "tutorial-gui-0": "这是你的主要资源。\n\n<color=#FF7078><size=25>材料</size></color>用于建造军队和建筑。\n\n<color=#FFFFFF><size=25>补给上限</size></color> — 维持地图上的部队。\n\n<color=#FF0000><size=25>零件</size></color>用于发展科技。\n\n<color=#99CDFF><size=25>网络功率</size></color>为建筑供能。",
    "tutorial-gui-1": "此区域取决于上下文。\n\n编组 — 选择普通单位时显示。\n\n选择带选项的建筑时 — 显示其选项。",
    "tutorial-gui-2": "建造建筑有第二个标签，包含特殊和防御建筑。\n\n按「~「（波浪号）切换标签。",
    "tutorial-gui-3": "此处显示能力（如有）。",
    "tutorial-gui-4": "点击单位图像将相机移至该单位。\n\n此处可设置按类型的攻击优先级。",
    "tutorial-gui-5": "使用热键选择单位的元素。显示在屏幕上。\n\nF1 — 所有建造者（移动建造中心和起重机）\nF2 — 所有战斗单位\nF3 — 所有单位",
    "tutorial-gui-6": "按住「Ctrl「或「T「+数字创建快捷编组。\n\n编组将出现在F2和F3的右侧。",
    "tutorial-basic-0": "建造建筑",
    "tutorial-basic-0a": "建造加工厂获取资源。兵营和军工厂用于生产军队。\n\n越多越好。你需要一个大型基地才能成功。",
    "tutorial-basic-0b": "要建造，请选择「移动建造中心「或「建筑起重机「。\n\n然后在打开的菜单中选择建筑并指定建造位置。",
    "tutorial-basic-0c": "要批量建造，请选择多个带选项的对象。\n\n按选项的快捷键，选择区域 — 系统将自动切换到下一个对象。",
    "tutorial-basic-1": "订购/生产单位",
    "tutorial-basic-1a": "生产部队。你的力量在于数量。\n\n管理资源，确保既有足够军队又有经济发展。",
    "tutorial-basic-2": "选择对象",
    "tutorial-basic-2a": "拖框选择建筑和单位。\n\n双击单位可选择地图上所有同类型单位。\n\nShift — 添加到选择。Ctrl — 从选择移除。",
    "tutorial-basic-3": "控制单位",
    "tutorial-basic-3a": "右键 — 移动到位置。\n\n按住G + 右键 — 倒车移动。\n\n注意：移动中无法射击的单位会忽略沿途敌人。",
    "tutorial-basic-4": "命令队列",
    "tutorial-basic-4a": "通过按住「Shift「键来排队命令。\n\n你也可以在战术暂停时下达命令。\n要开启战术暂停，按「空格「键。",
    "tutorial-basic-5": "移动攻击",
    "tutorial-basic-5a": "要让部队向指定位置推进而不忽略敌人，使用「移动攻击「命令。\n\n按「A「 + 左键点击地面。\n单位将开始移动并攻击沿途敌人。",
    "tutorial-basic-6": "集火攻击",
    "tutorial-basic-6a": "如果你需要集中火力攻击单个敌方目标：\n右键点击（不按「A「）敌人，所有单位将尝试到达并攻击该目标。",
    "tutorial-basic-7": "占领中立建筑",
    "tutorial-basic-7a": "步兵可以进入和驻守建筑，从内部开火。建筑容量显示在上方。\n\n这有助于防御性部署并提供额外视野。",
    "tutorial-basic-8": "能力",
    "tutorial-basic-8a": "单位和建筑有时可能有各种能力。\n\n例如，「移动建造中心「的能力允许其在地图上移动，从而在偏远地点建造。",
    "tutorial-basic-8b": "你有一个全局修理能力。\n\n它修理你的任何建筑，以及占领的民用建筑和可展开的大型单位（如移动建造中心或无畏舰）。\n\n要使用，按「B「并选择目标。",
    "tutorial-basic-9": "你随时可以通过点击此按钮返回此教程。\n\n祝好运。",
    "tutorial-reinforcements-0": "增援",
    "tutorial-reinforcements-1": "增援可以帮助你扭转战局。\n部队将到达指定地点。",
}

def translate_csv(input_path, output_path):
    """Read CSV, replace English column with Chinese, write output."""
    with open(input_path, 'r', encoding='utf-8-sig') as f:
        content = f.read()
    
    reader = csv.reader(io.StringIO(content))
    rows = list(reader)
    
    if not rows:
        print("Empty CSV!")
        return
    
    header = rows[0]
    print(f"Header: {header}")
    print(f"Total rows: {len(rows)}")
    
    translated_count = 0
    missing_count = 0
    missing_keys = []
    
    for i, row in enumerate(rows):
        if len(row) < 3:
            continue
        key = row[0].strip()
        if not key or key == 'Keys':
            continue
        
        if key in TRANSLATIONS:
            row[2] = TRANSLATIONS[key]  # Replace English (column 2) with Chinese
            translated_count += 1
        else:
            missing_count += 1
            missing_keys.append(key)
    
    print(f"Translated: {translated_count}")
    print(f"Missing: {missing_count}")
    if missing_keys:
        print(f"Missing keys: {missing_keys[:20]}...")
    
    # Write output
    with open(output_path, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(rows)
    
    print(f"Written to: {output_path}")

if __name__ == '__main__':
    # Process main localization file (textasset_164)
    input_164 = os.path.join(OUTPUT_DIR, 'textasset_164.csv')
    output_164 = os.path.join(OUTPUT_DIR, 'textasset_164_cn.csv')
    print("=" * 60)
    print("Processing main localization (textasset_164)...")
    translate_csv(input_164, output_164)
    
    # Process tutorial/demo file (textasset_165)
    input_165 = os.path.join(OUTPUT_DIR, 'textasset_165.csv')
    output_165 = os.path.join(OUTPUT_DIR, 'textasset_165_cn.csv')
    print("\n" + "=" * 60)
    print("Processing tutorial/demo (textasset_165)...")
    translate_csv(input_165, output_165)
